// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentPortal1.Data;

#nullable disable

namespace StudentPortal1.Migrations.ChallanDb
{
    [DbContext(typeof(ChallanDbContext))]
    [Migration("20241116142059_addlabeltran")]
    partial class addlabeltran
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DlvChln", b =>
                {
                    b.Property<int>("Challanno")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("Challansrno")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("Itemcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Pono")
                        .HasColumnType("int");

                    b.Property<int>("Posrno")
                        .HasColumnType("int");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Challanno", "Challansrno");

                    b.HasIndex("Pono", "Posrno");

                    b.ToTable("DlvChlns");
                });

            modelBuilder.Entity("LabeTran", b =>
                {
                    b.Property<int>("LabelSrNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LabelSrNo"));

                    b.Property<int>("ChallanNo")
                        .HasColumnType("int");

                    b.Property<int>("ChallanSrNo")
                        .HasColumnType("int");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LabelNo")
                        .HasColumnType("int");

                    b.Property<int>("PONo")
                        .HasColumnType("int");

                    b.Property<int>("POSrNo")
                        .HasColumnType("int");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("LabelSrNo");

                    b.ToTable("LabeTrans");
                });

            modelBuilder.Entity("StudentPortal1.Models.Domain.PoDtl", b =>
                {
                    b.Property<int>("Pono")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("Posrno")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("Cono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MfgUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Pono", "Posrno");

                    b.ToTable("PoDtls");
                });

            modelBuilder.Entity("StudentPortal1.Models.Dtos.ChallanSplitResultDto", b =>
                {
                    b.Property<int>("Challanno")
                        .HasColumnType("int");

                    b.Property<int>("Challansrno")
                        .HasColumnType("int");

                    b.Property<string>("Itemcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LabelQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Pono")
                        .HasColumnType("int");

                    b.Property<int>("Posrno")
                        .HasColumnType("int");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("labelno")
                        .HasColumnType("int");

                    b.ToTable("ChallanSplitResults");
                });

            modelBuilder.Entity("DlvChln", b =>
                {
                    b.HasOne("StudentPortal1.Models.Domain.PoDtl", "PoDtl")
                        .WithMany("DlvChlns")
                        .HasForeignKey("Pono", "Posrno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PoDtl");
                });

            modelBuilder.Entity("StudentPortal1.Models.Domain.PoDtl", b =>
                {
                    b.Navigation("DlvChlns");
                });
#pragma warning restore 612, 618
        }
    }
}
